# permissions for end users to view milvusstandalones.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: milvusstandalone-viewer-role
rules:
- apiGroups:
  - milvus.io.milvus.io
  resources:
  - milvusstandalones
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - milvus.io.milvus.io
  resources:
  - milvusstandalones/status
  verbs:
  - get
