
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - milvus.io.milvus.io
  resources:
  - milvusstandalones
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - milvus.io.milvus.io
  resources:
  - milvusstandalones/finalizers
  verbs:
  - update
- apiGroups:
  - milvus.io.milvus.io
  resources:
  - milvusstandalones/status
  verbs:
  - get
  - patch
  - update
